project_id = "bxxcyngrwsnrcsozrzno"

[functions.football-match-detail]
verify_jwt = false

[functions.match-analysis]
verify_jwt = false

[functions.football-fixtures]
verify_jwt = false

[functions.send-sms-aliyun]
verify_jwt = false